FROM python:3.11

WORKDIR /app

# Installer les dépendances en premier (cache Docker)
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Variables de développement
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV PYTHONUNBUFFERED=1

# Le code source est monté par bind mount, pas copié
# On expose le port de l'application
EXPOSE 5000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]