apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
stringData:
  DATABASE_URL: "postgresql://produser:prodpass@postgres:5432/proddb"
  SECRET_KEY: "une-cle-secrete-longue-et-aleatoire-pour-la-prod"